%% Постоянные
m = 2;
k = 17;

%% Палитра
dark       = [0.0039, 0.0275, 0.2118];
navy       = [0.0510, 0.1098, 0.2588];
blue       = [0.1333, 0.2235, 0.4353];
background = [1.0000, 1.0000, 1.0000];

%% Выбираем прямоугольник построения
a_min = -4;
a_max = 4;
b_min = 13;
b_max = 21;

%% Создаём сетку на комплексной плоскости
a_values = linspace(a_min, a_max, 1200);
b_values = linspace(b_min, b_max, 1200);
[A, B] = meshgrid(a_values, b_values);

% –––––

%% Вычисляем расстояния до центров окружностей
% Расстояние от точки (a, b) до точки (0, -m)
distance_first = sqrt(A.^2 + (B + m).^2);
% Расстояние от точки (a, b) до точки (0, k)
distance_second = sqrt(A.^2 + (B - k).^2);

%% Проверяем условия двух областей и находим их пересечение
% Первая область: |z + mi| > k
area_first = distance_first > k;
% Вторая область: |z - ki| < m
area_second = distance_second < m;
% Точка входит в пересечение, если выполняются оба условия
area_intersection = area_first & area_second;

%% Проверяем полученный результат
assert(isequal(area_intersection, area_second));
disp('Пересечение совпадает с кругом |z - 17i| < 2.');

% –––––

%% Окно рисунка
figure_handle = figure( ...
    'Color', background, ...
    'Position', [100, 100, 1050, 700]);

axes_handle = axes( ...
    'Parent', figure_handle, ...
    'Color', background);

hold(axes_handle, 'on');

%% Закрашиваем пересечение двух областей
[~, intersection_plot] = contourf( ...
    axes_handle, ...
    A, ...
    B, ...
    double(area_intersection), ...
    [0.5, 1.5], ...
    'LineStyle', 'none');
intersection_plot.FaceColor = blue;
intersection_plot.FaceAlpha = 0.88;

%% Граница первой области: sqrt(a^2 + (b + m)^2) = k
[~, first_boundary_plot] = contour( ...
    axes_handle, ...
    A, ...
    B, ...
    distance_first, ...
    [k, k], ...
    'Color', dark, ...
    'LineStyle', '--', ...
    'LineWidth', 2.0);

%% Граница второй области: sqrt(a^2 + (b - k)^2) = m
[~, second_boundary_plot] = contour( ...
    axes_handle, ...
    A, ...
    B, ...
    distance_second, ...
    [m, m], ...
    'Color', navy, ...
    'LineStyle', '--', ...
    'LineWidth', 2.0);

%% Центр второй окружности: (0, k)
center_plot = scatter( ...
    axes_handle, ...
    0.0, ...
    k, ...
    70, ...
    dark, ...
    'x', ...
    'LineWidth', 2.0);

%% Общую точка границ: (0, k - m)
common_point_plot = scatter( ...
    axes_handle, ...
    0.0, ...
    k - m, ...
    75, ...
    'o', ...
    'MarkerFaceColor', background, ...
    'MarkerEdgeColor', dark, ...
    'LineWidth', 2.0);

%% Мнимая ось
imaginary_axis = plot( ...
    axes_handle, ...
    [0.0, 0.0], ...
    [b_min, b_max], ...
    'Color', dark, ...
    'LineWidth', 0.8);
imaginary_axis.HandleVisibility = 'off';

%% Границы и масштаб рисунка
xlim(axes_handle, [a_min, a_max]);
ylim(axes_handle, [b_min, b_max]);
axis(axes_handle, 'equal');
axis(axes_handle, [a_min, a_max, b_min, b_max]);

%% Подписи и координатная сетка
xlabel(axes_handle, '$a=\operatorname{Re}z$', 'Interpreter', 'latex');
ylabel(axes_handle, '$b=\operatorname{Im}z$', 'Interpreter', 'latex');
title(axes_handle, 'Пересечение областей на комплексной плоскости');

grid(axes_handle, 'on');
axes_handle.GridColor = navy;
axes_handle.GridAlpha = 0.18;

% –––––

%% Легенда
legend( ...
    axes_handle, ...
    [intersection_plot, first_boundary_plot, second_boundary_plot, center_plot, common_point_plot], ...
    { ...
        'Пересечение: |z+2i|>17 и |z-17i|<2', ...
        'Граница |z+2i|=17 (не входит)', ...
        'Граница |z-17i|=2 (не входит)', ...
        'Центр второй окружности (0,17)', ...
        'Общая точка границ (0,15) (не входит)' ...
    }, ...
    'Location', 'southoutside', ...
    'Color', background, ...
    'EdgeColor', navy, ...
    'FontSize', 9);

hold(axes_handle, 'off');
